name: Metadata

on:
  push:
    branches:
      - main
    paths:
      - metadata.json
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: node -v
      - run: npm -v
      - uses: actions/checkout@v5
      - id: metadata
        run: |
          json=$(cat metadata.json | jq -c)
          echo "json=${json}" >> "$GITHUB_OUTPUT"
      - id: relays
        run: |
          echo "data<<EOF" >> "$GITHUB_OUTPUT"
          cat relays.json | jq -c -r '.[]' >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - uses: snow-actions/nostr@v1.8.1
        with:
          kind: 0
          content: ${{ steps.metadata.outputs.json }}
          relays: ${{ steps.relays.outputs.data }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
        id: publish
      - run: echo "$event" | jq > docs/metadata.json
        env:
          event: ${{ steps.publish.outputs.event }}
      - uses: snow-actions/git-config-user@v1.0.0
      - run: |
          set -x
          git add docs/
          git commit -m 'Update metadata.json'
          git push
      - run: |
          curl -X POST -u "${auth}" -H "Content-Type: application/json" -d "$event" https://nostr-webhook.compile-error.net/post
        env:
          event: ${{ steps.publish.outputs.event }}
          auth: ${{ secrets.NOSTR_WEBHOOK_BASIC_AUTH }}
